// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('compose', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('compose', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.linkText("COMPOSE")).click()
    await driver.findElement(By.name("postTitle")).click()
    await driver.findElement(By.name("postTitle")).sendKeys("Software testing")
    await driver.findElement(By.name("postBody")).click()
    await driver.findElement(By.name("postBody")).sendKeys("asfbablfbasfbalsbflblasbfililasf")
    await driver.findElement(By.name("button")).click()
  })
})
